(()=>{'use strict';const $=id=>document.getElementById(id),C=$('preview'),ctx=C.getContext('2d'),ROLES=['主C','回能','輔助','擊破','治療'],STAT=['生命','攻擊','物防','回能','魔防','擊破'],KEY='aniimo-team-card-prototype-02',images=new Map();let current=0,drawId=0;
const defaults={title:'我的搶蛋隊',purpose:'搶蛋',player:'UberEats⁶',note:'擊破開路，回能接力，主C收尾。',design:'cute',background:'beach',customBackground:'',shade:64,accent:'#b95e96',cardStyle:'light',showStats:true,scales:[15000,1000,600,600,600,600]};
function blank(){return{id:'',name:'尚未選擇',image:'',form:'一般形態',level:1,stars:0,potential:'',item:'',itemPlus:null,mbti:'',roles:[],note:'',stats:Array(6).fill(null),demo:false};}
function example(){const names=['輝月狐','貝瑟斯','熒冰龍','熒冰龍'],values=[[10867,717,254,343,240,407],[8400,480,310,520,340,290],[12100,430,460,370,420,360],[10300,520,370,400,440,320]],roles=[['主C'],['回能','輔助'],['擊破'],['治療']];return names.map((n,i)=>{const d=TeamDex.find(d=>d.name===n)||TeamDex[i];return{...blank(),...d,level:i===2?54:60,form:'一般形態',stars:[3,2,1,2][i],potential:['已激發','已激發 2 次','已激發 1 次','未激發'][i],item:['自訂攜帶物','回能配置','擊破配置','治療配置'][i],itemPlus:[5,3,2,4][i],mbti:['ISTJ','ENFP','ISFJ','INFJ'][i],roles:roles[i],note:['主要輸出，隊友回能後接爆發','提供能量，維持隊伍循環','先打出擊破，再交給主C','補足續航，穩定推進'][i],stats:values[i],demo:true};});}
let state={...defaults,members:example()};

function reference(m){const d=TeamDex.find(d=>d.id===m.id),head=d?.image.match(/Wiki_Aniimo_(\d+)/)?.[1],entry=TeamLevelData.data[head];if(!entry)return{reason:'這隻伊莫尚無可核對的等級參考資料。'};if(!['一般形態','基礎形態','基礎型態','Basic Form',''].includes(m.form))return{reason:'目前參考值適用一般形態；自訂或其他形態保留實際數字，不推算比例。'};if(m.level<1||m.level>60)return{reason:'目前已核對的參考換算範圍為 Lv.1–60；此等級保留實際數字，不外推。'};return{values:entry.level60.map((v,i)=>Math.round(v*(1-TeamLevelData.coefficient[i]*(60-m.level)))),source:entry.source};}
function ratios(m){const b=reference(m).values;return b?m.stats.map((v,i)=>v===null?null:v/b[i]):null;}
function radarLimit(){const values=state.members.flatMap(m=>ratios(m)||[]).filter(v=>Number.isFinite(v));return Math.max(2,Math.ceil(Math.max(0,...values)*1.2*2)/2);}
function baselineUI(){const m=state.members[current],b=reference(m),box=$('baselineTable');box.replaceChildren();$('fillBaseline').disabled=!b.values;$('baselineStatus').textContent=b.values?'Lv.'+m.level+' · 一般形態 · 未含培養加成的參考換算':b.reason;if(!b.values)return;const table=el('table'),head=el('tr');for(const title of ['能力','參考值','你的數值','差異'])head.append(el('th',title));const thead=el('thead');thead.append(head);table.append(thead);const body=el('tbody');b.values.forEach((v,i)=>{const tr=el('tr'),actual=m.stats[i],delta=actual===null?null:(actual/v-1)*100;for(const label of [STAT[i],v.toLocaleString('zh-TW'),actual===null?'—':actual.toLocaleString('zh-TW'),delta===null?'—':(delta>0?'+':'')+delta.toFixed(1)+'%'])tr.append(el('td',label));body.append(tr)});table.append(body);box.append(table);}

function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function pic(src){if(!src)return null;if(!images.has(src)){const im=new Image(),entry={image:im,ok:false,promise:null};entry.promise=new Promise(resolve=>{im.onload=()=>{entry.ok=true;queueDraw();resolve(true);};im.onerror=()=>resolve(false);});images.set(src,entry);im.src=src;}return images.get(src);}
function queueDraw(){if(drawId)return;drawId=requestAnimationFrame(()=>{drawId=0;render();});}
function number(value,min=0,max=1000000){return value===''?null:Math.max(min,Math.min(max,Number(value)||0));}
function status(t){$('status').textContent=t;}
function tabs(){const root=$('slotTabs');root.replaceChildren();state.members.forEach((m,i)=>{const b=el('button',undefined,'slot-tab'+(current===i?' active':''));b.type='button';b.setAttribute('role','tab');b.setAttribute('aria-selected',String(i===current));b.setAttribute('aria-controls','chosen');b.id='slotTab'+i;if(m.image){const im=el('img');im.src=m.image;im.alt='';b.append(im);}else b.append(el('span','＋'));b.append(el('span',String(i+1).padStart(2,'0')+' '+(m.id?m.name:'空位')));b.addEventListener('click',()=>{current=i;edit();});root.append(b);});}
function roles(){for(const b of $('roles').children){const yes=state.members[current].roles.includes(b.textContent);b.classList.toggle('active',yes);b.setAttribute('aria-pressed',String(yes));}}
function edit(){const m=state.members[current];tabs();$('chosen').replaceChildren();if(m.image){const im=el('img');im.src=m.image;im.alt=m.name;$('chosen').append(im);}const text=el('div');text.append(el('strong',m.name),el('small',m.demo?'示範配置 · 請改成你的培養資訊':m.id?'已選伊莫 · 手填面板':'請先搜尋伊莫'));$('chosen').append(text);for(const [id,key]of [['form','form'],['level','level'],['stars','stars'],['potential','potential'],['item','item'],['itemPlus','itemPlus'],['mbti','mbti'],['memberNote','note']])$(id).value=m[key]??'';for(let i=0;i<6;i++)$('stat'+i).value=m.stats[i]??'';roles();$('dexSearch').value='';$('dexResults').hidden=true;baselineUI();queueDraw();}
function topForms(){$('cardStyle').disabled=!!state.design&&state.design!=='classic';for(const b of document.querySelectorAll('[data-design]'))b.setAttribute('aria-pressed',String(b.dataset.design===(state.design||'classic')));for(const [id,key]of [['teamTitle','title'],['purpose','purpose'],['player','player'],['teamNote','note'],['shade','shade'],['accent','accent'],['cardStyle','cardStyle']])$(id).value=state[key];$('showStats').checked=state.showStats;$('shadeValue').textContent=state.shade+'%';for(const b of document.querySelectorAll('[data-bg]'))b.classList.toggle('active',b.dataset.bg===state.background);}
function search(){const q=$('dexSearch').value.trim(),root=$('dexResults');root.replaceChildren();root.hidden=!q;if(!q)return;const matches=TeamDex.filter(d=>d.name.includes(q));for(const d of matches){const b=el('button',undefined,'dex-option');b.type='button';if(d.image){const im=el('img');im.src=d.image;im.alt='';b.append(im);}b.append(el('strong',d.name),el('span','＋'));b.addEventListener('click',()=>{state.members[current]={...blank(),...d};edit();status('已選 '+d.name+'；請填入自己的等級與遊戲面板數值。');});root.append(b);}if(!matches.length)root.append(el('p','目前圖鑑找不到這個名稱。','hint'));}
function pathRound(x,y,w,h,r){ctx.beginPath();if(state.design==='tech'){const c=Math.min(14,w/5,h/4);ctx.moveTo(x+c,y);ctx.lineTo(x+w,y);ctx.lineTo(x+w,y+h-c);ctx.lineTo(x+w-c,y+h);ctx.lineTo(x,y+h);ctx.lineTo(x,y+c);ctx.closePath();}else ctx.roundRect(x,y,w,h,state.design==='cute'?Math.min(30,h/2):r);}
function paw(x,y,scale,color){ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(0,4,11,9,0,0,Math.PI*2);ctx.fill();for(const [xx,yy,rr]of [[-11,-8,4],[-4,-14,4.5],[5,-14,4.5],[12,-7,4]]){ctx.beginPath();ctx.ellipse(xx,yy,rr,rr*1.25,xx/20,0,Math.PI*2);ctx.fill();}ctx.restore();}
function spark(x,y,r,color){ctx.save();ctx.translate(x,y);ctx.fillStyle=color;ctx.beginPath();for(let i=0;i<8;i++){const a=i*Math.PI/4-Math.PI/2,rr=i%2?r*.28:r;i?ctx.lineTo(Math.cos(a)*rr,Math.sin(a)*rr):ctx.moveTo(Math.cos(a)*rr,Math.sin(a)*rr);}ctx.closePath();ctx.fill();ctx.restore();}
function brackets(x,y,w,h,color){ctx.save();ctx.strokeStyle=color;ctx.lineWidth=3;for(const [xx,yy,sx,sy]of [[x,y,1,1],[x+w,y,-1,1],[x,y+h,1,-1],[x+w,y+h,-1,-1]]){ctx.beginPath();ctx.moveTo(xx,yy+20*sy);ctx.lineTo(xx,yy);ctx.lineTo(xx+26*sx,yy);ctx.stroke();}ctx.restore();}

function panel(x,y,w,h,fill,stroke='#365771',r=24){pathRound(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1.5;ctx.stroke();}}
function text(str,x,y,size=24,color='#fff',weight=500,max=1000,align='left'){str=String(str);ctx.font=`${weight} ${size}px AniimoCard, "Microsoft JhengHei", "Noto Sans CJK TC", sans-serif`;while(ctx.measureText(str).width>max&&size>14){size--;ctx.font=`${weight} ${size}px AniimoCard, "Microsoft JhengHei", "Noto Sans CJK TC", sans-serif`;}if(ctx.measureText(str).width>max){while(str.length&&ctx.measureText(str+'…').width>max)str=str.slice(0,-1);str+='…';}ctx.fillStyle=color;ctx.textAlign=align;ctx.textBaseline='middle';ctx.fillText(str,x,y);}
function pill(str,x,y,w,color='#56dcf3',fill='#123348'){panel(x,y,w,39,fill,color,10);text(str,x+w/2,y+20,19,color,650,w-12,'center');}
function hexColor(alpha){const hex=state.accent.replace('#','');return `rgba(${parseInt(hex.slice(0,2),16)},${parseInt(hex.slice(2,4),16)},${parseInt(hex.slice(4,6),16)},${alpha})`;}
function radar(m,cx,cy,r,fg,muted){const points=Array.from({length:6},(_,i)=>{const a=-Math.PI/2+i*Math.PI/3;return[Math.cos(a),Math.sin(a)]}),limit=radarLimit(),values=ratios(m);ctx.save();if(state.design==='cute'){ctx.beginPath();ctx.arc(cx,cy,r+13,0,Math.PI*2);ctx.fillStyle='#f5eaf677';ctx.fill();}const grid=state.design==='cute'?'#b594bd55':'#629ac455';ctx.strokeStyle=grid;ctx.lineWidth=1.5;for(let ring=1;ring<=4;ring++){ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(cx+x*r*ring/4,cy+y*r*ring/4):ctx.moveTo(cx+x*r*ring/4,cy+y*r*ring/4));ctx.closePath();ctx.stroke();}points.forEach(([x,y])=>{ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(cx+x*r,cy+y*r);ctx.stroke();});if(values){ctx.setLineDash([5,4]);ctx.strokeStyle=fg;ctx.globalAlpha=.55;ctx.lineWidth=2;ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(cx+x*r/limit,cy+y*r/limit):ctx.moveTo(cx+x*r/limit,cy+y*r/limit));ctx.closePath();ctx.stroke();ctx.globalAlpha=1;ctx.setLineDash([]);if(values.some(v=>v!==null)){ctx.beginPath();points.forEach(([x,y],i)=>{const v=(values[i]??0)/limit;i?ctx.lineTo(cx+x*r*v,cy+y*r*v):ctx.moveTo(cx+x*r*v,cy+y*r*v)});ctx.closePath();ctx.fillStyle=hexColor(.24);ctx.fill();ctx.strokeStyle=state.accent;ctx.lineWidth=3;ctx.stroke();points.forEach(([x,y],i)=>{if(values[i]===null)return;ctx.beginPath();ctx.arc(cx+x*r*values[i]/limit,cy+y*r*values[i]/limit,4,0,Math.PI*2);ctx.fillStyle=state.accent;ctx.fill()})}else text('面板待填',cx,cy,18,muted,500,150,'center');}else text('基準待補',cx,cy,18,muted,500,150,'center');points.forEach(([x,y],i)=>{const xx=cx+x*(r+38),yy=cy+y*(r+37);text(STAT[i],xx,yy-7,19,muted,500,95,'center');if(state.showStats)text(m.stats[i]===null?'—':m.stats[i].toLocaleString('zh-TW'),xx,yy+19,22,fg,750,120,'center');});ctx.restore();}
function drawPortrait(m,x,y,w,h,fg){const cache=pic(m.image);const grad=ctx.createLinearGradient(x,y,x+w,y+h);grad.addColorStop(0,hexColor(.16));grad.addColorStop(1,'#17354b05');panel(x,y,w,h,grad,null,25);if(cache?.ok){const im=cache.image,scale=Math.min((w-12)/im.width,(h-12)/im.height);ctx.drawImage(im,x+(w-im.width*scale)/2,y+(h-im.height*scale)/2,im.width*scale,im.height*scale);}else text(m.id?m.name.slice(0,1):'＋',x+w/2,y+h/2,70,fg,600,w,'center');}
function backgroundSrc(){return state.background==='custom'?state.customBackground:state.background==='beach'?'assets/beach.webp':state.background==='adventure'?'assets/adventure.webp':'';}
function render(){const cute=state.design==='cute',tech=state.design==='tech',light=cute||(!tech&&state.cardStyle==='light'),fg=light?'#403b57':'#edfaff',muted=light?'#80718c':'#8caec3',headerFg=cute?'#574461':'#f3faff',headerMuted=cute?'#876d85':'#bdd5e4';ctx.clearRect(0,0,1600,1520);const grad=ctx.createLinearGradient(0,0,1600,1520);grad.addColorStop(0,cute?'#fce5ed':tech?'#053647':'#153c59');grad.addColorStop(.45,cute?'#f9f4e9':'#071626');grad.addColorStop(1,cute?'#e4eef8':'#0e2940');ctx.fillStyle=grad;ctx.fillRect(0,0,1600,1520);const bg=pic(backgroundSrc());if(bg?.ok){const im=bg.image,scale=Math.max(1600/im.width,1520/im.height);ctx.drawImage(im,(1600-im.width*scale)/2,(1520-im.height*scale)/2,im.width*scale,im.height*scale);}ctx.fillStyle=cute?`rgba(255,248,248,${state.shade/100})`:`rgba(3,12,22,${state.shade/100})`;ctx.fillRect(0,0,1600,1520);
if(cute){for(let y=26;y<1520;y+=65)for(let x=25;x<1600;x+=65){ctx.beginPath();ctx.arc(x+(Math.floor(y/65)%2)*20,y,2.5,0,Math.PI*2);ctx.fillStyle='#aa6b9716';ctx.fill();}paw(1490,153,1.3,'#bb8aab55');spark(1188,88,20,'#b883a86b');spark(1470,1445,15,'#b883a86b');}else{ctx.strokeStyle=tech?hexColor(.085):'#b8ddf20f';ctx.lineWidth=1;for(let i=-1520;i<1600;i+=tech?64:90){ctx.beginPath();ctx.moveTo(i,0);ctx.lineTo(i+1520,1520);ctx.stroke();}if(tech){for(let y=0;y<1520;y+=64){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(1600,y);ctx.stroke();}brackets(20,20,1560,1480,hexColor(.55));ctx.fillStyle=hexColor(.06);for(let y=0;y<1520;y+=7)ctx.fillRect(0,y,1600,1);}}
text(cute?'MY ANIIMO · TEAM DIARY':tech?'ANIIMO // SQUAD INTERFACE':'ANIIMO · TEAM CARD',52,48,20,state.accent,650);text(state.title||'我的伊莫隊伍',52,104,52,headerFg,850,1050);text(state.note||'四隻伊莫，一套屬於你的玩法。',54,159,23,headerMuted,500,1230);pill(state.purpose+'隊伍',1290,36,254,state.accent,cute?'#fffaf0e8':'#091c32d9');text(state.player?'BY '+state.player:'MY TEAM',1546,112,24,headerMuted,650,400,'right');
state.members.forEach((m,i)=>{const x=52+(i%2)*766,y=207+Math.floor(i/2)*618,w=730,h=592;ctx.save();if(cute){ctx.shadowColor='#81597825';ctx.shadowBlur=22;ctx.shadowOffsetY=10;}else if(tech){ctx.shadowColor=hexColor(.2);ctx.shadowBlur=20;}panel(x,y,w,h,cute?'#fffdf7f2':light?'#eff7f5e6':tech?'#061726ef':'#071b2de8',cute?'#e4cbdc':light?'#c5dee8':tech?hexColor(.6):'#456d8880',cute?32:24);ctx.restore();if(tech){brackets(x+10,y+10,w-20,h-20,state.accent);ctx.fillStyle=state.accent;ctx.fillRect(x+26,y+109,84,3);text('UNIT / '+String(i+1).padStart(2,'0'),x+w-194,y+83,12,muted,500,168,'right');}if(cute){ctx.save();ctx.translate(x+61,y+4);ctx.rotate(-.08);panel(-23,-10,119,29,'#ecd5e9cf',null,2);ctx.restore();paw(x+w-34,y+h-25,.7,'#e8d4df');}
panel(x+24,y+22,42,33,cute?'#f6e0e9':tech?'#103b47':'#123344',null,10);text(String(i+1).padStart(2,'0'),x+45,y+38,18,state.accent,750,42,'center');text(m.name,x+80,y+37,34,fg,850,460);text(m.form||'一般形態',x+80,y+78,18,muted,500,460);pill('Lv.'+m.level,x+w-132,y+22,104,cute?'#996087':light?'#265972':'#8ce5f4',cute?'#f4e4f0':light?'#d7eef1':'#12334b');ctx.strokeStyle=cute?'#e6cfdf':light?'#8ba7b333':'#99c5e52b';ctx.beginPath();ctx.moveTo(x+26,y+106);ctx.lineTo(x+w-26,y+106);ctx.stroke();
if(cute){ctx.save();ctx.translate(x+145,y+235);ctx.rotate(-.045);panel(-121,-117,242,234,'#f4eafa','#e9d6ee',25);ctx.restore();spark(x+248,y+155,14,'#d9a3c4');spark(x+39,y+321,11,'#dcc180');}drawPortrait(m,x+32,y+131,225,208,fg);if(tech)brackets(x+33,y+132,223,206,hexColor(.55));radar(m,x+485,y+250,93,fg,muted);
let rx=x+32;for(const role of m.roles){pill(role,rx,y+355,86,state.accent,cute?'#f7e7ee':light?'#113b4c':'#143a4d');rx+=94;}if(!m.roles.length)text('定位未填',x+32,y+375,18,muted);const metaY=y+423;text('共鳴升星',x+32,metaY,18,muted);text(m.stars?'★'.repeat(Math.min(6,m.stars))+(m.stars>6?' +'+(m.stars-6):''):'未升星',x+160,metaY,22,m.stars?cute?'#b69047':'#f6d279':fg,650,195);text('潛能',x+384,metaY,18,muted);text(m.potential||'未填',x+464,metaY,21,fg,600,235);text('攜帶物',x+32,y+470,18,muted);text((m.item||'未填')+(m.item&&m.itemPlus!==null?' +'+m.itemPlus:''),x+160,y+470,22,fg,650,400);if(m.mbti)pill(m.mbti,x+w-123,y+452,91,cute?'#9c79b2':light?'#577099':'#bcc7ff',cute?'#eee5f5':light?'#edf0ff':'#26344a');text(m.note||'—',x+32,y+521,20,muted,500,w-64);text(m.demo?'DEMO · 示範配置':'PLAYER BUILD · 玩家配置',x+32,y+565,13,muted,500,500);});
text('伊莫隊伍名片',54,1479,18,headerMuted,650);text('虛線＝同級參考 · 實線＝玩家面板 · 外圈 '+radarLimit().toFixed(1)+'倍',800,1479,17,headerMuted,500,800,'center');text('UberEats⁶',1546,1479,20,state.accent,750,300,'right');}
for(const t of ROLES){const b=el('button',t);b.type='button';b.setAttribute('aria-pressed','false');b.addEventListener('click',()=>{const m=state.members[current],i=m.roles.indexOf(t);if(i<0)m.roles.push(t);else m.roles.splice(i,1);roles();queueDraw();});$('roles').append(b);}
for(let i=0;i<6;i++){const lab=el('label',STAT[i]),input=el('input');input.id='stat'+i;input.type='number';input.min=0;input.max=1000000;input.placeholder='填入遊戲數值';input.addEventListener('input',()=>{state.members[current].stats[i]=number(input.value);baselineUI();queueDraw();});lab.append(input);$('stats').append(lab);}
$('fillBaseline').addEventListener('click',()=>{const b=reference(state.members[current]);if(!b.values)return;state.members[current].stats=[...b.values];edit();status('已填入同等級參考值；可逐項改成遊戲中的實際面板。');});
for(const a of ['I','E'])for(const b of ['S','N'])for(const c of ['T','F'])for(const d of ['J','P']){const o=el('option',a+b+c+d);o.value=o.textContent;$('mbti').append(o);}
for(const [id,key]of [['form','form'],['level','level'],['stars','stars'],['potential','potential'],['item','item'],['itemPlus','itemPlus'],['mbti','mbti'],['memberNote','note']])$(id).addEventListener('input',()=>{const m=state.members[current];m[key]=id==='level'?Math.round(number($(id).value,1,100)||1):id==='stars'?Number($(id).value):id==='itemPlus'?number($(id).value,0,99):$(id).value;baselineUI();queueDraw();});
for(const [id,key]of [['teamTitle','title'],['purpose','purpose'],['player','player'],['teamNote','note'],['shade','shade'],['accent','accent'],['cardStyle','cardStyle']])$(id).addEventListener('input',()=>{state[key]=id==='shade'?Number($(id).value):$(id).value;$('shadeValue').textContent=state.shade+'%';queueDraw();});$('showStats').addEventListener('change',()=>{state.showStats=$('showStats').checked;queueDraw();});
$('dexSearch').addEventListener('input',search);$('dexSearch').addEventListener('keydown',e=>{if(e.key==='Escape')$('dexResults').hidden=true;if(e.key==='ArrowDown'){e.preventDefault();$('dexResults').querySelector('button')?.focus();}});
for(const b of document.querySelectorAll('[data-design]'))b.addEventListener('click',()=>{state.design=b.dataset.design;const p=state.design==='cute'?{accent:'#b95e96',shade:64,cardStyle:'light',bg:'beach'}:state.design==='tech'?{accent:'#45eddf',shade:66,cardStyle:'dark',bg:'blue'}:{accent:'#56dcf3',shade:65,cardStyle:'dark',bg:'adventure'};state.accent=p.accent;state.shade=p.shade;state.cardStyle=p.cardStyle;if(state.background!=='custom')state.background=p.bg;topForms();queueDraw();});
for(const b of document.querySelectorAll('[data-bg]'))b.addEventListener('click',()=>{state.background=b.dataset.bg;topForms();queueDraw();});
async function uploaded(input,which){const f=input.files[0];if(!f)return;if(f.size>15*1024*1024){status('圖片請小於 15 MB。');input.value='';return;}try{const raw=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(f);}),cache=pic(raw);if(!await cache.promise)throw Error();const im=cache.image,temp=document.createElement('canvas'),scale=Math.min(1,2000/Math.max(im.width,im.height));temp.width=Math.round(im.width*scale);temp.height=Math.round(im.height*scale);temp.getContext('2d').drawImage(im,0,0,temp.width,temp.height);const src=temp.toDataURL('image/png');if(which==='background'){state.customBackground=src;state.background='custom';topForms();}else{state.members[current].image=src;edit();}queueDraw();status('已套用圖片；只在本機處理。');}catch{status('無法讀取圖片，請使用 PNG、JPG 或 WebP。');}input.value='';}
$('portrait').addEventListener('change',()=>uploaded($('portrait'),'portrait'));$('backgroundUpload').addEventListener('change',()=>uploaded($('backgroundUpload'),'background'));$('clearMember').addEventListener('click',()=>{state.members[current]=blank();edit();status('已清空第 '+(current+1)+' 格。');});$('resetStats').addEventListener('click',()=>{state.members[current].stats=Array(6).fill(null);edit();});$('demo').addEventListener('click',()=>{state={...defaults,scales:[...defaults.scales],members:example()};current=0;topForms();edit();status('已載入排版範例；示範數值不代表伊莫基礎能力。');});
$('save').addEventListener('click',()=>{try{localStorage.setItem(KEY,JSON.stringify({schema:1,state}));status('草稿已儲存在這個瀏覽器。');}catch{status('草稿儲存失敗；自訂圖片可能太大，請先匯出 PNG。');}});
$('load').addEventListener('click',()=>{try{const saved=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem('aniimo-team-card-prototype-01'));if(saved?.schema!==1||saved.state?.members?.length!==4||saved.state?.scales?.length!==6)throw Error();state=saved.state;current=0;topForms();edit();status('已載入儲存的草稿。');}catch{status('這個瀏覽器尚無有效草稿。');}});
$('export').addEventListener('click',async()=>{const button=$('export');button.disabled=true;status('正在準備圖片…');try{const sources=[backgroundSrc(),...state.members.map(m=>m.image)].filter(Boolean);const entries=sources.map(pic);await Promise.all(entries.map(e=>e.promise));await document.fonts.ready;render();const blob=await new Promise(resolve=>C.toBlob(resolve,'image/png'));if(!blob)throw Error();const url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download=(state.title||'伊莫隊伍名片').replace(/[\\/:*?"<>|]/g,'-')+'.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('已匯出 1600 × 1520 PNG。');}catch{status('匯出失敗，請重新套用圖片後再試。');}finally{button.disabled=false;}});
window.TeamCard={getState:()=>state,render,reference,ratios,radarLimit};topForms();edit();document.fonts.ready.then(queueDraw);})();
